import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Nav from '@/components/Nav/Nav';
import { getUser } from '@/util/getUser';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Events-blog',
  description: 'Generated by Next.js',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  return (
    <html lang='en' className='bg-gray-800 h-full w-full flex justify-center'>
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
